# Generated by Django 4.2.3 on 2023-07-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='categories',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('meat', 'Meat')], max_length=50),
        ),
    ]
